config/routes.rb
Rails.application.routes.draw do

  # 顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  scope module: :public do
     root to: "homes#top"
     get 'homes/about' => 'homes#about'
     get '/customers/:id/leave' => 'customers#leave', as: 'leave'
     patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
     delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
     post '/orders/confirm' 
     get '/orders/complete'
     
     resources :customers, only: [:show, :edit, :update, :leave, :withdrawl, :destroy]
     resources :items, only: [:index, :show]
     resources :cart_items, only: [:index, :create, :update, :destroy]
     resources :orders, only: [:new, :index, :show, :complete, :create]
     resources :destinations, only: [:index, :create, :edit, :update, :destroy]
     
  end
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
  root to: 'homes#top'
  #get 'home/top' => 'homes#top', as: ' '
  resources :items, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item
   belongs_to :customer
   
  def subtotal
    item.with_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy
         has_many :destinations, dependent: :destroy
         
  def name
    self.last_name + " " + self.first_name
  end
  
  def kana
    self.last_name_kana + " " + self.first_name_kana
  end
  
  #def active_for_authentication?
    #super && (is_deleted == false)
  #end
  
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :customer
  
  def destination_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
  
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  
    has_many :cart_items, dependent: :destroy
    
    has_one_attached :image
    
  def with_tax_price
    (price * 1.1).floor
  end
  
   def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
   end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  belongs_to :customer
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  
  def tax_included
    (price * 1.1).to_i
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    @orders = Order.all
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def show
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.all
    @item = Item.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
  if @item.save
     flash[:notice] = "Item was successfully created."
    redirect_to admin_items_path
  else
     @items = Item.all
     render :index
  end
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
   if   @item.update(item_params)
    flash[:notice] = "Book was successfully updated."
    redirect_to admin_items_path
   else
    render :edit
   end
  end
  
  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :image, :price)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def show
    @order = Order.find(params[:id])
  end
  
private
  def order_params
    params.require(:order).permit(:payment_method, :postcode, :address, :name)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path # ログアウト後に遷移するpathを設定
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  #   before_action :configure_permitted_parameters, if: :devise_controller



  # protected

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <% if admin_signed_in? %>
      <p><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %> </p>
      <p><%= link_to "顧客一覧", admin_customers_path %></p>
      <p><%= link_to "商品一覧", admin_items_path %></p>
      <p><%= link_to "注文履歴", admin_root_path %></p>

    <% elsif customer_signed_in? %>
      <p><%= link_to "ログアウト", destroy_customer_session_path, method: :delete %></p>
      <p><%= link_to "商品一覧", items_path %></p>
      <p><%= link_to "カート", cart_items_path(current_customer.id) %></p>
      <p><%= link_to "マイページ", customer_path(current_customer.id) %></p>

    <% else  %>
      <p><%= link_to "新規登録", new_customer_registration_path %></p>
      <p><%= link_to "ログイン", new_customer_session_path %></p>
      <p><%= link_to "商品一覧", items_path %></p>
      <p><%= link_to "About", homes_about_path %></p>
    <% end %>
  </header>
    <%= yield %>
  </body>
</html>